package conductance.core.material;

import java.util.function.Function;
import java.util.function.Predicate;
import lombok.RequiredArgsConstructor;
import conductance.api.material.Material;
import conductance.api.material.MaterialGenerationHandler;

@RequiredArgsConstructor
final class MaterialGenerationHandlerImpl implements MaterialGenerationHandler {

	private final Function<Material, String> unlocalizedNameFactory;
	private final boolean hasItem;
	private final boolean hasBlock;
	private final boolean hasFluid;
	private final boolean autoGenerated;
	private final Predicate<Material> predicate;

	@Override
	public boolean hasItem() {
		return this.hasItem;
	}

	@Override
	public boolean hasBlock() {
		return this.hasBlock;
	}

	@Override
	public boolean hasFluid() {
		return this.hasFluid;
	}

	@Override
	public boolean isAutoGenerated() {
		return this.autoGenerated;
	}

	@Override
	public String getUnlocalizedName(final Material material) {
		return this.unlocalizedNameFactory.apply(material);
	}

	@Override
	public boolean test(final Material material) {
		return this.predicate.test(material);
	}
}
