package conductance.core.material;

import java.util.HashSet;
import java.util.Set;
import java.util.function.Function;
import java.util.function.Predicate;
import net.minecraft.resources.ResourceLocation;
import lombok.RequiredArgsConstructor;
import conductance.api.material.Material;
import conductance.api.material.MaterialGenerationHandler;
import conductance.api.material.event.MaterialGenerationHandlerBuilder;

@RequiredArgsConstructor
final class MaterialGenerationHandlerBuilderImpl implements MaterialGenerationHandlerBuilder {

	private final Set<ResourceLocation> groupTags = new HashSet<>();
	private final Set<String> entryTags = new HashSet<>();
	private final Function<Material, String> unlocalizedNameFactory;
	private Predicate<Material> predicate = ignored -> true;
	private boolean hasItem = false;
	private boolean hasBlock = false;
	private boolean hasFluid = false;
	private boolean autoGenerated = false;


	@Override
	public MaterialGenerationHandlerBuilder groupTag(final String tagName) {
		this.groupTags.add(ResourceLocation.parse(tagName));
		return this;
	}

	@Override
	public MaterialGenerationHandlerBuilder entryTag(final String tagName) {
		this.entryTags.add(tagName);
		return this;
	}

	@Override
	public MaterialGenerationHandlerBuilder setObjectData(final boolean hasItem, final boolean hasBlock, final boolean hasFluid) {
		this.hasItem = hasItem;
		this.hasBlock = hasBlock;
		this.hasFluid = hasFluid;
		return this;
	}

	@Override
	public MaterialGenerationHandlerBuilder setAutoGenerated(final boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
		return this;
	}

	@Override
	public MaterialGenerationHandlerBuilder predicate(final Predicate<Material> predicate) {
		this.predicate = predicate;
		return this;
	}

	public MaterialGenerationHandler build() {
		return new MaterialGenerationHandlerImpl(
				this.unlocalizedNameFactory,
				this.hasItem, this.hasBlock, this.hasFluid, this.autoGenerated,
				this.predicate
		);
	}
}
