package conductance.api.material;

public interface MaterialGenerationHandler {

	boolean hasItem();

	boolean hasBlock();

	boolean hasFluid();

	boolean isAutoGenerated();

	String getUnlocalizedNameFactory();

	default String getUnlocalizedName(final Material material) {
		return this.getUnlocalizedNameFactory().formatted(material.getName());
	}

	boolean test(Material material);
}
