package conductance.api.material;

public interface MaterialGenerationHandler {

	boolean hasItem();

	boolean hasBlock();

	boolean hasFluid();

	boolean isAutoGenerated();

	String getUnlocalizedName(Material material);

	boolean test(Material material);
}
