package conductance.api.material.event;

import java.util.function.Predicate;
import conductance.api.material.Material;
import conductance.api.material.MaterialFlag;

public interface MaterialGenerationHandlerBuilder {

	MaterialGenerationHandlerBuilder groupTag(String tagName);

	MaterialGenerationHandlerBuilder entryTag(String tagName);

	MaterialGenerationHandlerBuilder setObjectData(boolean hasItem, boolean hasBlock, boolean hasFluid);

	MaterialGenerationHandlerBuilder setAutoGenerated(boolean autoGenerated);

	MaterialGenerationHandlerBuilder predicate(Predicate<Material> predicate);

	default MaterialGenerationHandlerBuilder requiredFlag(final MaterialFlag requiredFlag) {
		return this.predicate(material -> material.hasFlag(requiredFlag));
	}
}
