package conductance.init;

import conductance.api.NCMaterialFlags;
import conductance.api.NCMaterialGenerationHandlers;
import conductance.api.material.event.RegisterMaterialGenerationHandlerEvent;
import conductance.api.plugin.ConductancePluginListener;
import conductance.api.plugin.EventListener;
import conductance.Conductance;

@ConductancePluginListener(modid = Conductance.MODID)
public final class ConductanceMaterialGenerationHandlers {

	@EventListener(priority = -100)
	private static void init(final RegisterMaterialGenerationHandlerEvent event) {
		NCMaterialGenerationHandlers.DUST = event.register("dust", b -> b
				.groupTag("c:dusts")
				.entryTag("c:dusts/%s")
				.setObjectData(true, false, false)
				.setAutoGenerated(true)
				.requiredFlag(NCMaterialFlags.DUST)
		);
		NCMaterialGenerationHandlers.INGOT = event.register("ingot", b -> b
				.groupTag("c:ingots")
				.entryTag("c:ingots/%s")
				.setObjectData(true, false, false)
				.setAutoGenerated(true)
				.requiredFlag(NCMaterialFlags.INGOT)
		);
		NCMaterialGenerationHandlers.GEM = event.register("gem", "%s", b -> b
				.groupTag("c:gems")
				.entryTag("c:gems/%s")
				.setObjectData(true, false, false)
				.setAutoGenerated(true)
				.requiredFlag(NCMaterialFlags.GEM)
		);
	}

	private ConductanceMaterialGenerationHandlers() {
	}
}
