package conductance.init;

import conductance.api.NCPeriodicElements;
import conductance.api.periodicelement.event.RegisterPeriodicElementEvent;
import conductance.api.plugin.ConductancePluginListener;
import conductance.api.plugin.EventListener;
import conductance.Conductance;

@ConductancePluginListener(modid = Conductance.MODID)
final class ConductancePeriodicElements {

	@EventListener(priority = -100)
	private static void init(final RegisterPeriodicElementEvent event) {
		NCPeriodicElements.HYDROGEN = event.create(1, 0, "Hydrogen", "H", null);
		NCPeriodicElements.DEUTERIUM = event.create(1, 1, "Deuterium", "D", NCPeriodicElements.HYDROGEN);
		NCPeriodicElements.TRITIUM = event.create(1, 2, "Tritium", "T", NCPeriodicElements.HYDROGEN);
		NCPeriodicElements.HELIUM = event.create(2, 2, "Helium", "He", null);
		NCPeriodicElements.HELIUM_3 = event.create(2, 1, "Helium-3", "He-3", NCPeriodicElements.HELIUM);
		NCPeriodicElements.LITHIUM = event.create(3, 4, "Lithium", "Li", null);
		NCPeriodicElements.BERYLLIUM = event.create(4, 5, "Beryllium", "Be", null);
		NCPeriodicElements.BORON = event.create(5, 5, "Boron", "B", null);
		NCPeriodicElements.CARBON = event.create(6, 6, "Carbon", "C", null);
		NCPeriodicElements.NITROGEN = event.create(7, 7, "Nitrogen", "N", null);
		NCPeriodicElements.OXYGEN = event.create(8, 8, "Oxygen", "O", null);
		NCPeriodicElements.FLUORINE = event.create(9, 9, "Fluorine", "F", null);
		NCPeriodicElements.NEON = event.create(10, 10, "Neon", "Ne", null);
		NCPeriodicElements.SODIUM = event.create(11, 11, "Sodium", "Na", null);
		NCPeriodicElements.MAGNESIUM = event.create(12, 12, "Magnesium", "Mg", null);
		NCPeriodicElements.ALUMINIUM = event.create(13, 13, "Aluminium", "Al", null);
		NCPeriodicElements.SILICON = event.create(14, 14, "Silicon", "Si", null);
		NCPeriodicElements.PHOSPHORUS = event.create(15, 15, "Phosphorus", "P", null);
		NCPeriodicElements.SULFUR = event.create(16, 16, "Sulfur", "S", null);
		NCPeriodicElements.CHLORINE = event.create(17, 18, "Chlorine", "Cl", null);
		NCPeriodicElements.ARGON = event.create(18, 22, "Argon", "Ar", null);
		NCPeriodicElements.POTASSIUM = event.create(19, 20, "Potassium", "K", null);
		NCPeriodicElements.CALCIUM = event.create(20, 20, "Calcium", "Ca", null);
		NCPeriodicElements.SCANDIUM = event.create(21, 24, "Scandium", "Sc", null);
		NCPeriodicElements.TITANIUM = event.create(22, 26, "Titanium", "Ti", null);
		NCPeriodicElements.VANADIUM = event.create(23, 28, "Vanadium", "V", null);
		NCPeriodicElements.CHROMIUM = event.create(24, 28, "Chrome", "Cr", null);
		NCPeriodicElements.MANGANESE = event.create(25, 30, "Manganese", "Mn", null);
		NCPeriodicElements.IRON = event.create(26, 30, "Iron", "Fe", null);
		NCPeriodicElements.COBALT = event.create(27, 32, "Cobalt", "Co", null);
		NCPeriodicElements.NICKEL = event.create(28, 30, "Nickel", "Ni", null);
		NCPeriodicElements.COPPER = event.create(29, 34, "Copper", "Cu", null);
		NCPeriodicElements.ZINC = event.create(30, 35, "Zinc", "Zn", null);
		NCPeriodicElements.GALLIUM = event.create(31, 39, "Gallium", "Ga", null);
		NCPeriodicElements.GERMANIUM = event.create(32, 40, "Germanium", "Ge", null);
		NCPeriodicElements.ARSENIC = event.create(33, 42, "Arsenic", "As", null);
		NCPeriodicElements.SELENIUM = event.create(34, 45, "Selenium", "Se", null);
		NCPeriodicElements.BROMINE = event.create(35, 45, "Bromine", "Br", null);
		NCPeriodicElements.KRYPTON = event.create(36, 48, "Krypton", "Kr", null);
		NCPeriodicElements.RUBIDIUM = event.create(37, 48, "Rubidium", "Rb", null);
		NCPeriodicElements.STRONTIUM = event.create(38, 49, "Strontium", "Sr", null);
		NCPeriodicElements.YTTRIUM = event.create(39, 50, "Yttrium", "Y", null);
		NCPeriodicElements.ZIRCONIUM = event.create(40, 51, "Zirconium", "Zr", null);
		NCPeriodicElements.NIOBIUM = event.create(41, 53, "Niobium", "Nb", null);
		NCPeriodicElements.MOLYBDENUM = event.create(42, 53, "Molybdenum", "Mo", null);
		NCPeriodicElements.TECHNETIUM = event.create(43, 55, "Technetium", "Tc", null);
		NCPeriodicElements.RUTHENIUM = event.create(44, 57, "Ruthenium", "Ru", null);
		NCPeriodicElements.RHODIUM = event.create(45, 58, "Rhodium", "Rh", null);
		NCPeriodicElements.PALLADIUM = event.create(46, 60, "Palladium", "Pd", null);
		NCPeriodicElements.SILVER = event.create(47, 60, "Silver", "Ag", null);
		NCPeriodicElements.CADMIUM = event.create(48, 64, "Cadmium", "Cd", null);
		NCPeriodicElements.INDIUM = event.create(49, 65, "Indium", "In", null);
		NCPeriodicElements.TIN = event.create(50, 68, "Tin", "Sn", null);
		NCPeriodicElements.ANTIMONY = event.create(51, 70, "Antimony", "Sb", null);
		NCPeriodicElements.TELLURIUM = event.create(52, 75, "Tellurium", "Te", null);
		NCPeriodicElements.IODINE = event.create(53, 74, "Iodine", "I", null);
		NCPeriodicElements.XENON = event.create(54, 77, "Xenon", "Xe", null);
		NCPeriodicElements.CAESIUM = event.create(55, 77, "Caesium", "Cs", null);
		NCPeriodicElements.BARIUM = event.create(56, 81, "Barium", "Ba", null);
		NCPeriodicElements.LANTHANUM = event.create(57, 81, "Lanthanum", "La", null);
		NCPeriodicElements.CERIUM = event.create(58, 82, "Cerium", "Ce", null);
		NCPeriodicElements.PRASEODYMIUM = event.create(59, 81, "Praseodymium", "Pr", null);
		NCPeriodicElements.NEODYMIUM = event.create(60, 84, "Neodymium", "Nd", null);
		NCPeriodicElements.PROMETHIUM = event.create(61, 83, "Promethium", "Pm", null);
		NCPeriodicElements.SAMARIUM = event.create(62, 88, "Samarium", "Sm", null);
		NCPeriodicElements.EUROPIUM = event.create(63, 88, "Europium", "Eu", null);
		NCPeriodicElements.GADOLINIUM = event.create(64, 93, "Gadolinium", "Gd", null);
		NCPeriodicElements.TERBIUM = event.create(65, 93, "Terbium", "Tb", null);
		NCPeriodicElements.DYSPROSIUM = event.create(66, 96, "Dysprosium", "Dy", null);
		NCPeriodicElements.HOLMIUM = event.create(67, 97, "Holmium", "Ho", null);
		NCPeriodicElements.ERBIUM = event.create(68, 99, "Erbium", "Er", null);
		NCPeriodicElements.THULIUM = event.create(69, 99, "Thulium", "Tm", null);
		NCPeriodicElements.YTTERBIUM = event.create(70, 103, "Ytterbium", "Yb", null);
		NCPeriodicElements.LUTETIUM = event.create(71, 103, "Lutetium", "Lu", null);
		NCPeriodicElements.HAFNIUM = event.create(72, 106, "Hafnium", "Hf", null);
		NCPeriodicElements.TANTALUM = event.create(73, 107, "Tantalum", "Ta", null);
		NCPeriodicElements.TUNGSTEN = event.create(74, 109, "Tungsten", "W", null);
		NCPeriodicElements.RHENIUM = event.create(75, 111, "Rhenium", "Re", null);
		NCPeriodicElements.OSMIUM = event.create(76, 114, "Osmium", "Os", null);
		NCPeriodicElements.IRIDIUM = event.create(77, 115, "Iridium", "Ir", null);
		NCPeriodicElements.PLATINUM = event.create(78, 117, "Platinum", "Pt", null);
		NCPeriodicElements.GOLD = event.create(79, 117, "Gold", "Au", null);
		NCPeriodicElements.MERCURY = event.create(80, 120, "Mercury", "Hg", null);
		NCPeriodicElements.THALLIUM = event.create(81, 123, "Thallium", "Tl", null);
		NCPeriodicElements.LEAD = event.create(82, 125, "Lead", "Pb", null);
		NCPeriodicElements.BISMUTH = event.create(83, 125, "Bismuth", "Bi", null);
		NCPeriodicElements.POLONIUM = event.create(84, 124, "Polonium", "Po", null);
		NCPeriodicElements.ASTATINE = event.create(85, 124, "Astatine", "At", null);
		NCPeriodicElements.RADON = event.create(86, 134, "Radon", "Rn", null);
		NCPeriodicElements.FRANCIUM = event.create(87, 134, "Francium", "Fr", null);
		NCPeriodicElements.RADIUM = event.create(88, 136, "Radium", "Ra", null);
		NCPeriodicElements.ACTINIUM = event.create(89, 136, "Actinium", "Ac", null);
		NCPeriodicElements.THORIUM = event.create(90, 140, "Thorium", "Th", null);
		NCPeriodicElements.PROTACTINIUM = event.create(91, 138, "Protactinium", "Pa", null);
		NCPeriodicElements.URANIUM_238 = event.create(92, 146, "Uranium-238", "U-238", null);
		NCPeriodicElements.URANIUM_235 = event.create(92, 143, "Uranium-235", "U-235", NCPeriodicElements.URANIUM_238);
		NCPeriodicElements.NEPTUNIUM = event.create(93, 144, "Neptunium", "Np", null);
		NCPeriodicElements.PLUTONIUM_239 = event.create(94, 145, "Plutonium-239", "Pu-239", null);
		NCPeriodicElements.PLUTONIUM_241 = event.create(94, 149, "Plutonium-241", "Pu-241", NCPeriodicElements.PLUTONIUM_239);
		NCPeriodicElements.AMERICIUM = event.create(95, 150, "Americium", "Am", null);
		NCPeriodicElements.CURIUM = event.create(96, 153, "Curium", "Cm", null);
		NCPeriodicElements.BERKELIUM = event.create(97, 152, "Berkelium", "Bk", null);
		NCPeriodicElements.CALIFORNIUM = event.create(98, 153, "Californium", "Cf", null);
		NCPeriodicElements.EINSTEINIUM = event.create(99, 153, "Einsteinium", "Es", null);
		NCPeriodicElements.FERMIUM = event.create(100, 157, "Fermium", "Fm", null);
		NCPeriodicElements.MENDELEVIUM = event.create(101, 157, "Mendelevium", "Md", null);
		NCPeriodicElements.NOBELIUM = event.create(102, 157, "Nobelium", "No", null);
		NCPeriodicElements.LAWRENCIUM = event.create(103, 159, "Lawrencium", "Lr", null);
		NCPeriodicElements.RUTHERFORDIUM = event.create(104, 161, "Rutherfordium", "Rf", null);
		NCPeriodicElements.DUBNIUM = event.create(105, 163, "Dubnium", "Db", null);
		NCPeriodicElements.SEABORGIUM = event.create(106, 165, "Seaborgium", "Sg", null);
		NCPeriodicElements.BOHRIUM = event.create(107, 163, "Bohrium", "Bh", null);
		NCPeriodicElements.HASSIUM = event.create(108, 169, "Hassium", "Hs", null);
		NCPeriodicElements.MEITNERIUM = event.create(109, 167, "Meitnerium", "Mt", null);
		NCPeriodicElements.DARMSTADTIUM = event.create(110, 171, "Darmstadtium", "Ds", null);
		NCPeriodicElements.ROENTGENIUM = event.create(111, 169, "Roentgenium", "Rg", null);
		NCPeriodicElements.COPERNICIUM = event.create(112, 173, "Copernicium", "Cn", null);
		NCPeriodicElements.NIHONIUM = event.create(113, 171, "Nihonium", "Nh", null);
		NCPeriodicElements.FLEROVIUM = event.create(114, 175, "Flerovium", "Fl", null);
		NCPeriodicElements.MOSCOVIUM = event.create(115, 173, "Moscovium", "Mc", null);
		NCPeriodicElements.LIVERMORIUM = event.create(116, 177, "Livermorium", "Lv", null);
		NCPeriodicElements.TENNESSINE = event.create(117, 177, "Tennessine", "Ts", null);
		NCPeriodicElements.OGANESSON = event.create(118, 176, "Oganesson", "Og", null);
	}

	private ConductancePeriodicElements() {
	}
}
