package conductance.init;

import net.minecraft.world.item.Item;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;
import conductance.api.CAPI;
import conductance.api.material.Material;
import conductance.Conductance;
import conductance.core.CreativeTabHelper;

public final class ConductanceItems {

	private static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(Conductance.MODID);

	public static void initialize(final IEventBus modEventBus) {
		ConductanceItems.REGISTRY.register(modEventBus);
		CAPI.regs().materials().forEach(ConductanceItems::generateMaterial);
	}

	private static void generateMaterial(final Material material) {
		CAPI.regs().materialGenerationHandlers().stream()
				.filter(handler -> handler.hasItem() && handler.isAutoGenerated() && handler.test(material))
				.forEach(handler -> {
					ConductanceItems.REGISTRY.registerItem(handler.getUnlocalizedName(material), props -> {
						final Item item = new Item(props);
						CreativeTabHelper.addToTab(item, CreativeTabHelper.Tabs.GENERAL);
						return item;
					});
				});
	}

	private ConductanceItems() {
	}
}
